### ISSUE TITLE
A couple PGO+BOLT limitations worth documenting?

### ISSUE THREAD

**Issue by mcronce** [Kobzol/cargo-pgo#26]
In order to get PGO+BOLT working, I needed to
* Switch from fat LTO to thin
* Disable `strip = "symbols"` in my release profile
* Use trunk LLVM (you already have this in the README, this is just to affirm that it's still needed - I was trying with the 15.0.4 tag previously)

Is it worth documenting those, and/or is there a way to make those settings work in `RUSTFLAGS` when you build the PGO-optimized binary that you're going to pass to `llvm-bolt --instrument`?  The errors come from `cc`, which makes them _super_ cryptic and unhelpful; I found the workarounds by just throwing possible fixes at the wall until something stuck :joy:

I can retrigger the errors tonight if having a copy of them would be helpful

**Comment by mcronce** [comment]
PS - thanks for the hard work on this!  Your code in this repo and in the BOLT PRs for rustlang/rust are _literally_ the only documentation I can find on using BOLT with Rust

**Comment by mcronce** [comment]
Never mind the LTO bit; fat LTO is now not (even close to) worth the compile time hit to this project with the addition of BOLT, but it looks like it wasn't an actual blocking issue, only the `strip` piece and LLVM version were.

**Comment by Kobzol** [comment]
Hi! Thanks for the useful information. In theory, `cargo-pgo` could detect symbol stripping/fat LTO and warn the user about it. With LLVM version, it's a bit more difficult, because it's probably impossible for the plugin to detect whether a specific LLVM version will work or not :sweat_smile:

**Comment by Kobzol** [comment]
I added a warning about stripping symbols when using BOLT to the README. Let me know if you think that I should document more things.

**Comment by mcronce** [comment]
I think that gets the job done.  Hopefully it saves somebody some time :)
