### ISSUE TITLE
PGO for non-terminating programs

### ISSUE THREAD

**Issue by flippette** [Kobzol/cargo-pgo#27]
So I have a server that is supposed to run forever. How can I gather instrumentation data for such a program?

**Comment by Kobzol** [comment]
Hi :) I think that the easiest way is just to execute your server with PGO, then let it run for some time on a representative workload (e.g. if it was a HTTP server, you can simulate some client load or just let it be used by clients for an hour).

It seems that currently if the PGO instrumented program exits abruptly, the profiles might not be saved. So the safest option is probably to just add some hard limit to your service (like end after N requests or after N minutes) and then gather profiles in this special limited mode.

There are also some other, more sophisticated ways, for example continually profiling the server in production and reoptimizing it regularly, but that's quite complex (example from Google: https://static.googleusercontent.com/media/research.google.com/cs//pubs/archive/36575.pdf).
