### ISSUE TITLE
Github action

### ISSUE THREAD

**Issue by FilipAndersson245** [Kobzol/cargo-pgo#34]
Hello, I wanted to configure a github action to generate pgo optimized releases, but did not find good resources on doing that.
Also would it be reasonable to make a cargo-pgo action so it becomes simpler for more people to apply pgo to their code?

**Comment by Kobzol** [comment]
I thought about this a bit more and I think that it would be quite challenging to create a single action that could handle all the possible PGO/BOLT use-cases. I decided instead to create an example PGO workflow that you can find [here](https://github.com/Kobzol/cargo-pgo/blob/main/ci/pgo.yml). Let me know if it helps you.
