### ISSUE TITLE
can't find crate for `profiler_builtins`

### ISSUE THREAD

**Issue by Demontf** [Kobzol/cargo-pgo#41]
Hi excuse me,
I just use a hello world project(only have one file main.rs) to learning the PGO
under the project when I execute `cargo pgo build` meet this

errror[E0463]: can't find crate for `profiler_builtins`
  |
  = note: the compiler may have been built without the profiler runtime

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `ww` due to 2 previous errors
[2023-12-05T16:47:31Z ERROR cargo_pgo::pgo::instrument] PGO instrumentation build has failed.
Cargo finished with an error (101)

But there is no package named profiler_builtins in crates.io

**Comment by Kobzol** [comment]
Hi, `profiler_builtins` is a rustc compiler crate that implements profiling instrumentation. If it's not available, then your Rust toolchain or platform probably doesn't support PGO.
