### ISSUE TITLE
Does not allow for optimizations for WASM targets

### ISSUE THREAD

**Issue by GeeWee** [Kobzol/cargo-pgo#42]
I have a WASM server-side project I'd love to try out PGO on. Unfortunately it does not seem to work. E.g. running the command
```bash
cargo pgo instrument build -- --bin my-binary--release --target wasm32-wasi
```

results in the error
```
error[E0463]: can't find crate for `profiler_builtins`
```

however, the same command without the `--target` does not provoke the same error.

I do not necessarily think this is anything cargo-pgo can do anything about - I believe the underlying issue is [this one](https://github.com/rust-lang/rust/issues/81684). I figured I'd create an issue anyways, in case I was wrong, or anyone else came looking for the same information.

**Comment by Kobzol** [comment]
Yeah, this is not related to this crate. That error simply means that this specific target is not distributed with support for PGO. Either because this target doesn't support it, or simply because we just don't build and ship it on CI via rustup.

**Comment by GeeWee** [comment]
That makes sense. Feel free to close, but just wanted to point this out if someone else came searching for it :)
