### ISSUE TITLE
cargo-pgo ignores all rustflags defined in config.toml file, how to pass custom rustflags to pgo build?

### ISSUE THREAD

**Issue by Wyvern** [Kobzol/cargo-pgo#49]
Looks like `cargo pgo [optimize] build` ignores rustflags in config.toml file, is there a way to pass it to PGO subcommand?

**Comment by Kobzol** [comment]
Hi, this has been already reported [here](https://github.com/Kobzol/cargo-pgo/issues/18). Could you just pass these flags manually in RUSTFLAGS? It's not trivial to append rustflags in `cargo pgo` without overriding `.cargo/config.toml`.

**Comment by Wyvern** [comment]
But my `rustflags=[...]` in `config.toml` is very long, pass it through `env var` is NOT convenient. Furthermore, there is `profile based rustflags` which can switch between different profiles. Put everything in `RUSTFLAGS` is not a reasonable approach.

**Comment by Kobzol** [comment]
I see. I did consult this with the Cargo developers and we didn't find a much better way. So perhaps this will require cargo-pgo to parse config.toml to make this work.

Out of curiosity, how do you use per-profile rustflags? Didn't you mean per-target?

**Comment by Wyvern** [comment]
Cargo has already supported `[unstable.profile-rustflags = true]` option.
https://github.com/rust-lang/cargo/issues/10271
https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option

**Comment by Kobzol** [comment]
Oh, it's unstable! Cool.

I think that I have an idea how this could be done. I also battled with overriding rustflags in https://github.com/Kobzol/cargo-remark, and there the solution was to use `cargo build --config build.rustflags=[]` (see discussion [here](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Passing.20Rustflags.20with.20spaces/near/408432242)). I will try it.

**Comment by Kobzol** [comment]
Okay, it seems to work! But the `--config` parameter is unstable :( You can try

```bash
$ cargo install --git https://github.com/kobzol/cargo-pgo --branch append-to-rustflags
```
If it works for you.

**Comment by Kobzol** [comment]
Oh, my bad, it's not actually unstable. I was just testing with `1.56.1`, which is the minimum supported version by `cargo-pgo`. So I will be able to just check the Rust version and use `RUSTFLAGS` or `--config` based on it, good! So please just confirms if this works for you.

**Comment by Wyvern** [comment]
And also `[host.rustflags]` detection when cargo's 
```
[unstable]
host-config = true
target-applies-to-host = true
```
is applied. 
IIRC, `[host.rustflags]` will override `[build.rustflags]`.

**Comment by Wyvern** [comment]
Maybe the entire chain of rustflags should be `{build, host, target.'cfg(all())', target.*, profile.*}.rustflags`.

**Comment by Wyvern** [comment]
Well, `host.rustflags` cover more areas than `build.rustflags` such as build.rs and macro optimization. If `pgo` subcommand only support build.rustflags, it's ok for now. But it's a burden for developers to have to duplicate the rustflags in both [host] and [build] sections. And currently, cargo already ignored `build.rustflags` when you use `host.rustflags`, so all `cargo-*` subcommand should follow this convention to align with cargo's behavior pattern.

So the better option is, [host] first if not fall back to [build] to read rustflags.

**Comment by Kobzol** [comment]
Where is `host.rustflags` documented? I only see `build` and `target.<XYZ>` [here](https://doc.rust-lang.org/cargo/reference/config.html#configuration-format).
