### ISSUE TITLE
Shall we have a Docker image for convenience?

### ISSUE THREAD

**Issue by bioinformatist** [Kobzol/cargo-pgo#51]
I can work for it. BTW, is it necessary for creating a Discord channel?

**Comment by Kobzol** [comment]
Hi, what use case do you see for a Docker container? So that it contains precompiled BOLT? That could be indees useful I suppose :)

I don't understand the Discord question.

**Comment by bioinformatist** [comment]
Yeah container with precompiled BOLT binarys will be very useful I think. Discord channel is just for discussion. Let me try to submit a PR for Dockerfile or even workflow for CI.

**Comment by bioinformatist** [comment]
It's nearly be finished! But I need additional 2~3 days for testing and CI.

![image](https://github.com/Kobzol/cargo-pgo/assets/17194719/46263d96-34f0-442c-a6c6-a996bd2002e8)
